### ISSUE TITLE
When to release code

### ISSUE THREAD

**Issue by ForrestPi** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#1]
Is there any plan to release the source code?

**Comment by ForrestPi** [comment]
@aashishrai3799 Is there any plan to release the source code?

**Comment by aashishrai3799** [comment]
Hey! Thanks for your interest in our work. We are currently working on significantly improving the quality of the texture. You can expect to see the new results and perhaps the testing code in the coming weeks. Thank you!

**Comment by ForrestPi** [comment]
@aashishrai3799 Thank You for Replying

**Comment by abhigoku10** [comment]
@aashishrai3799  when shall be source code realse ?? amazing work

**Comment by aashishrai3799** [comment]
Hey! We'll be releasing the code shortly. Perhaps, in the next two weeks or so.

**Comment by SlimeVRX** [comment]
Thanks for the great job! Look forward!

**Comment by SlimeVRX** [comment]
@aashishrai3799 Please notify here when you release the code.

**Comment by boboyiyi** [comment]
您发给我的信件已经收到。谢谢!

**Comment by 4d5645** [comment]
@aashishrai3799 Hi, are your plans to release the code still valid?

**Comment by aashishrai3799** [comment]
Thank you for your interest in our project. We appreciate your patience as we work to release the code.

We have been experiencing some internal concerns that have caused a delay in the release. We are working diligently to address these concerns and are confident that the code will be released soon.

We are committed to releasing the code as soon as possible. 

Thank you again for your interest.

**Comment by SlimeVRX** [comment]
Thanks for your great work!

**Comment by SlimeVRX** [comment]
@aashishrai3799 Hello, are your plans to release the code still valid?

**Comment by boboyiyi** [comment]
您发给我的信件已经收到。谢谢!

**Comment by SlimeVRX** [comment]
Hi, is your code release plan still valid? Look forward!

**Comment by pyh007** [comment]
代码多久发布啊！！ 期待

**Comment by aashishrai3799** [comment]
Thank you once more for expressing your interest in our work. Unfortunately, we have encountered unexpected circumstances that have led to the postponement of the code release. As of now, we do not have a specific timeline for when it will be available.

Rest assured, we will keep our webpage updated with any developments regarding the code release.

**Comment by SlimeVRX** [comment]
No problem! Thanks for your great work!

**Comment by pyh007** [comment]
> 再次感谢您对我们工作表示关注。不幸的是，我们遇到了意想不到的情况，导致代码发布推迟。截至目前，我们还没有具体的时间表。
> 
> 请放心，我们将随时更新我们的网页，了解有关代码发布的任何进展。

请问下代码多久发布啊！！！ 期待

**Comment by boboyiyi** [comment]
您发给我的信件已经收到。谢谢!

**Comment by chnegh6666** [comment]
Amazing work！When will the code be published?

**Comment by pyh007** [comment]
你好啊，多久发布代码

**Comment by CIntellifusion** [comment]
hello, I am looking forward to your early realease of your amazing work.

**Comment by BlockchainPunks** [comment]
I'm calling bullshit on this project - promise after promise for many months and no code - just excuses.


broken or not you shouldn't make promises you can't keep

**Comment by BukenyaLukman** [comment]
Honestly guys, release that code. If at all that is okay with you. Because we have waited for months now.

**Comment by aashishrai3799** [comment]
Hi everyone,

I extend my sincere apologies for the delay in uploading the code. I have been engrossed in other projects, leaving me with limited time to complete this task. I assure you that I will upload the inference code by midnight today (EST) and will endeavor to release the training code shortly thereafter.

Your patience and continued interest in our work are greatly appreciated.

Best regards,
Aashish Rai

**Comment by abhigoku10** [comment]
@aashishrai3799   Thanks for the response request u to upload the training code and the pretrained models also 

Thanks in advance and looking forward to ur latest work !!

**Comment by aashishrai3799** [comment]
Hi, I've updated the link!
