### ISSUE TITLE
can this run on windows and linux?

### ISSUE THREAD

**Issue by BlockchainPunks** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#15]
running the following on windows anaconda install:
conda env create -f environment.yaml

throws errors;
<img width="311" alt="Windows" src="https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/97580331/ac8a1b1e-a31b-4fd3-a5db-cf28cd58008c">

If not:

Which version of Linux did you use?
Which version of Python did you use?
Which version of Conda did you use?

**Comment by aashishrai3799** [comment]
Hi, we used Conds 4.14.0, and ran our experiments on Python 3.6 and 3.9.
