### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by misakamage** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#18]
Hi! I think I've resolved the dependencies in Colab, but when running the demo, I encountered this error. Do you know how to solve it?
![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/65758136/42afc331-4379-498c-a8a9-10a41c9798dd)

**Comment by aashishrai3799** [comment]
Hi. It seems like verts_uvs is empty. Can you check what all is stored in aux?

**Comment by misakamage** [comment]
I print aux, and return
Properties(normals=None, verts_uvs=None, material_colors=None, texture_images=None, texture_atlas=None) . 
It looks like nothing stored in aux?

Additionally, I think this error might be related to the 'head_template.obj' file. Is the 'head_template.obj' file here the same as the one in MICA?

OK I solve this problem, this file is the one in DECA.

**Comment by miaoYuanyuan** [comment]
> I print aux, and return Properties(normals=None, verts_uvs=None, material_colors=None, texture_images=None, texture_atlas=None) . It looks like nothing stored in aux?
> 
> Additionally, I think this error might be related to the 'head_template.obj' file. Is the 'head_template.obj' file here the same as the one in MICA?
> 
> OK I solve this problem, this file is the one in DECA.

could you tell me  how  you solve this problem?

**Comment by misakamage** [comment]
把deca项目里的那个head_template.obj文件放进去就行了





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aashishrai3799/Towards-Realistic-Generative-3D-Face-Models"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月2日(星期二) 下午4:15
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models] TypeError: 'NoneType' object is not subscriptable (Issue #18)





  
I print aux, and return Properties(normals=None, verts_uvs=None, material_colors=None, texture_images=None, texture_atlas=None) . It looks like nothing stored in aux?
 
Additionally, I think this error might be related to the 'head_template.obj' file. Is the 'head_template.obj' file here the same as the one in MICA?
 
OK I solve this problem, this file is the one in DECA.
  
could you tell me  how  you solve this problem?
