### ISSUE TITLE
Why is mesh and texture quality terrible doesn’t match the video quality for this project

### ISSUE THREAD

**Issue by BlockchainPunks** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#21]
Reference to this - runs project on Colab https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/issues/20#issuecomment-1864728161

the quality is terrible and doesn’t match your demo??? 

Without demo outputs it’s impossible to tell if that’s expected or not. ( your demo video shows near perfect face texture and mesh? Why does this code not produce the same results

**Comment by aashishrai3799** [comment]
demo results released
