### ISSUE TITLE
Teeth/ mouth

### ISSUE THREAD

**Issue by Inferencer** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#23]
Interesting results thank you for uploading them.

I notice partial teeth appear in the 'rendered' images however the detailed mesh appears pretty well tracked so is the partial teeth a result of the textures or the mesh or both?

**Comment by aashishrai3799** [comment]
Hi, the irregularity in teeth detection stems from the facial landmark detection algorithm we use. While it generally performs fine, there are instances where it falls short of accurately detecting landmarks on certain faces.

**Comment by Inferencer** [comment]
Ok so not ideal for a frame sequence good to know ty again
