### ISSUE TITLE
About REALY benchmark results

### ISSUE THREAD

**Issue by misakamage** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#24]
Hi! Thank you for your results.  If possible, could you share the detailed results of your work on REALY, such as REALY_error.txt? It would be very helpful for my work. I tried reconstructing REALY using your demo and obtained poor results; I'm not sure if it's due to my own error.

**Comment by aashishrai3799** [comment]
Hi, sure. Here are the reconstructions for REALY Benchmark - [[LINK](https://drive.google.com/file/d/1jxVHSjvgom4ZyyajKCgC3jxhvDXvFdGY/view?usp=sharing)]

**Comment by misakamage** [comment]
> Hi, sure. Here are the reconstructions for REALY Benchmark - [[LINK](https://drive.google.com/file/d/1jxVHSjvgom4ZyyajKCgC3jxhvDXvFdGY/view?usp=sharing)]

Thank you! And Do I need to use FLAME as the template_topology?

**Comment by aashishrai3799** [comment]
Yes, please use the FLAME topology for coarse results.
