### ISSUE TITLE
The result create by pretrain modal is bad

### ISSUE THREAD

**Issue by wengjincheng** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#25]
HI, I have download everything this project need and run reconstruct: python demos/demo_reconstruct.py

But the result is bad(I just compare it with Deep3D Pytorch):

![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/20600119/f7a94519-3e04-4745-839c-645629a4d2ab)

VS

![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/20600119/aed7f98c-5a2f-4633-9840-74a7415e70a6)

I think that maybe the pretrain modal you released is wrong

**Comment by aashishrai3799** [comment]
Hi, are you getting similar artifacts with other images as well?

**Comment by wengjincheng** [comment]
> Hi, are you getting similar artifacts with other images as well?

yeah

**Comment by aashishrai3799** [comment]
Hi, thanks for letting me know. Could you please try again with the updated file [deca.py](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/blob/main/decalib/deca.py)?

**Comment by wengjincheng** [comment]
@aashishrai3799 uv texture map still bad.
![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/20600119/f42ce891-64bc-447c-a9da-b136409419ae)

But the shape seems correct except the color

![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/20600119/c93ded55-bf4f-4544-ad2c-e6e7d6123e26)

**Comment by aashishrai3799** [comment]
Hi, the color issue is due to RGB and BGR channel arrangement in CV2 and PIL. You can use cv2.cvtColor(img, cv2.COLOR_BGR2RGB) to get the proper colors in the output. I'll also correct the inference code.
