### ISSUE TITLE
Why is inputpath not inputpath?

### ISSUE THREAD

**Issue by wynsmile** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#27]
It works great, I'm new, can you guide me to run python demos/ demo_generation.py file input path is what, Why is it that when I modify the image in -i', '--inputpath', default='inference_test/in_data', the output is not my image?

**Comment by aashishrai3799** [comment]
Hi, demo_generation.py is to generate new synthetic 3D faces. --inputpath is of no use in this case. You can use demo_reconstruct.py to reconstruct your own images.

**Comment by wynsmile** [comment]
Thank you very much for your reply, I already know.
