### ISSUE TITLE
FFHQ textures

### ISSUE THREAD

**Issue by Oocean35** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#3]
Hi @aashishrai3799 , 

Thanks for sharing your work! 
Since you cannot share the code, I was wondering if you could share a dataset of ffhq textures instead ? That would be super helpful ! 
Thanks a lot !!

Best regards

**Comment by aashishrai3799** [comment]
Hi. You can use the img_2_tex.py to generate textures from 2D images.
