### ISSUE TITLE
The results varied widely

### ISSUE THREAD

**Issue by wenxy68** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#5]
Hello author, I found that the resultant effect is very different during my experiment.Do you know the reason? And when are you going to publish the training codes.Thank you so much.The specific comparison chart is shown below: 
![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/48885367/c4ac22e9-fcd9-433e-be1e-4160314a380d)
![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/48885367/bfa2daf0-31f6-4f26-8ca1-b8d226c6e471)

**Comment by aashishrai3799** [comment]
Hi, do you mean why the model generates artifacts/kids?
Please correct me if I'm getting it wrong.

**Comment by wenxy68** [comment]
Hello author, I am using the pre-trained weight file as shown below:
![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/48885367/e8514806-9b8b-479f-a614-8d7187a7fbe7)
![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/48885367/41da728b-4c82-4ad3-abe8-4a3bd44bd5ac)

**Comment by aashishrai3799** [comment]
Hi, the issue appears to be with the StyleGAN2 generator, as it's producing faces with artifacts while sampling some corner cases. Try to play around with truncation and truncation_latent to generate better results.

**Comment by BlockchainPunks** [comment]
any chance you can share the steps you followed to get this up and running. The install instructions are riddled with issues and hoping someone who managed to get it working to provide their steps to setup. Issues appear to be linked to most of the steps related to copy & pasting external files into this projects folder structure before running the scripts. I cannot get the author of this repo to provide exact steps just 1 liners that aren't helping.
