### ISSUE TITLE
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

### ISSUE THREAD

**Issue by misakamage** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#6]
Thanks for your great work!
 I want to run your demo in colab. And I have put antelopev2.zip in /insightface/models. 
However, it still returns information indicating a failure to download the corresponding file. How should I resolve this issue?

**Comment by aashishrai3799** [comment]
Hi, I'd suggest putting the model in ./insightface for the module to load it locally.

**Comment by misakamage** [comment]
Thank you for your reply! You mean I should put the model like this ?
![image](https://github.com/aashishrai3799/Towards-Realistic-Generative-3D-Face-Models/assets/65758136/153f4944-e40d-4aa9-829a-4ccd139ff5b2)
