### ISSUE TITLE
Can I use my own photos with your model without retraining?

### ISSUE THREAD

**Issue by BlockchainPunks** [aashishrai3799/Towards-Realistic-Generative-3D-Face-Models#7]
CN I use my own photos with your model without retraining?

When will training code be available? Months weeks years?

**Comment by aashishrai3799** [comment]
Hi. Yes, you can use your photos to reconstruct 3D faces without retraining the model. Simply replace the "-inputpath" argument with your images' folder path in "demos/demo_reconstruct.py".
